routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', function () {
    return view('web.login');
});
/*Route::prefix("private")->name("private.")->namespace("Admin")->group(function(){
	
	Route::get('/login', 'Auth\LoginController@showLoginForm');
	Route::post('/login-user', 'Auth\LoginController@login')->name('login');
	Route::get('/register', 'Auth\RegisterController@showRegistrationForm');
	Route::post('/store', 'Auth\RegisterController@register')->name('register');
	Route::get('/logout', 'Auth\LoginController@logout')->name('logout');
});*/


Auth::routes();
Route::middleware('auth')->group( function(){
	//User Routes
	Route::get('users',"UserController@index")->name("users");
	Route::post('user/list',"UserController@getList")->name("user.list");
	Route::post('user/count', "UserController@userCount")->name("user.count");
	Route::get('myProfile', "UserController@myProfile")->name("user.profile");
	Route::post('user/status', "UserController@updateStatus")->name("user.status");
	Route::post('user/block', "UserController@updateBlock")->name("user.block");
	Route::post('user/destroy',"UserController@destroy")->name("user.destroy");
	Route::post('profile-update', "UserController@profileUpdate")->name("user.profileUpdate");
	Route::post('password-update', "UserController@passwordUpdate")->name("user.passwordUpdate");

	//Main Folder Route
	Route::post('/add-mainfolder',"MainFolderController@store")->name("users.main-folder");
	Route::post('/get-mainfolder',"MainFolderController@getList")->name("users.get-mainfolder");
	Route::post('/edit-mainfolder',"MainFolderController@edit")->name("users.edit-mainfolder");
	Route::put('/update-mainfolder/{mainFolder}', 'MainFolderController@update')->name('users.update-mainfolder');
	Route::get('/get-folder/{mainFolder}', 'MainFolderController@show')->name('users.show');

	Route::get('/logout', function(){
		auth()->logout();
		return redirect('/')->cookie(cookie()->forget('user_id'));
	});
});

Route::get('admin/login', 'Admin\Auth\LoginController@showLoginForm')->name('admin.login');
Route::post('/login-user', 'Admin\Auth\LoginController@login')->name('admin.login.user');

Route::prefix("private")->middleware('auth:admin')->name("private.")->namespace("Admin")->group( function(){
	Route::get('dashboard', "DashboardController@index")->name('dashboard');
	Route::get('/home', 'AdminController@index')->name('home');
	//Route::get('/login', 'Auth\LoginController@showLoginForm')->name('form');
	//Route::post('/login-user', 'Auth\LoginController@login')->name('login');
	Route::get('/register', 'Auth\RegisterController@showRegistrationForm');
	Route::post('/store', 'Auth\RegisterController@register')->name('register');
	Route::get('/logout', 'Auth\LoginController@logout')->name('logout');

	/*//Admin User related Routes
	Route::get('adminuser/list', "AdminUserController@index")->name("adminusers");
	Route::post('adminuser/list', "AdminUserController@getList")->name("adminuser.list");
	Route::post('adminuser/create', "AdminUserController@create")->name("adminuser.create");
	Route::post('adminuser/edit', "AdminUserController@edit")->name("adminuser.edit");
	Route::post('adminuser/update', "AdminUserController@update")->name("adminuser.update");
	Route::post('adminuser/status', "AdminUserController@updateStatus")->name("adminuser.status");
	Route::post('adminuser/destroy', "AdminUserController@destroy")->name("adminuser.destroy");
	Route::get('adminuser/profile/{key}', "AdminUserController@viewProfile")->name("adminuser.profile");
	
	Route::post('password-update', "AdminUserController@passwordUpdate")->name("passwordUpdate");
	Route::post('profile-update', "AdminUserController@profileUpdate")->name("profileUpdate");*/
	Route::get('adminuser/list', "AdminUserController@index")->name("adminusers");
    Route::get('my-profile', "AdminUserController@myProfile")->name("myprofile");
    Route::post('password-update', "AdminUserController@passwordUpdate")->name("passwordUpdate");
	Route::post('profile-update', "AdminUserController@profileUpdate")->name("profileUpdate");
	Route::post('dashboard-chart', "AdminUserController@barChart")->name('dashboard.chart');

	//Admin User Type Routes
	Route::get('admin-type', "AdminTypeController@index")->name("admintypes");
	Route::post('admin-type/list', "AdminTypeController@getUserTypeList")->name("admintype.list");
	Route::post('admin-type/create', "AdminTypeController@create")->name("admintype.create");
	Route::post('admin-type/edit', "AdminTypeController@edit")->name("admintype.edit");
	Route::post('admin-type/update', "AdminTypeController@update")->name("admintype.update");
	Route::post('admin-type/status', "AdminTypeController@updateStatus")->name("admintype.status");
	Route::post('admin-type/destroy', "AdminTypeController@destroy")->name("admintype.destroy");


	//Question Routes
	Route::get('question', "QuestionController@index")->name("questions")->middleware("ican:question.view");
	Route::post('question/list', "QuestionController@getList")->name("question.list")->middleware("ican:question.view");
	Route::post('question/create', "QuestionController@create")->name("question.create")->middleware("ican:question.create");
	Route::post('question/edit', "QuestionController@edit")->name("question.edit")->middleware("ican:question.edit");
	Route::post('question/update', "QuestionController@update")->name("question.update")->middleware("ican:question.edit");
	Route::post('question/status', "QuestionController@updateStatus")->name("question.status")->middleware("ican:question.edit");
	Route::post('question/destroy', "QuestionController@destroy")->name("question.destroy")->middleware("ican:question.delete");

	//User Routes
	Route::get('users',"UserController@index")->name("users");
	Route::post('user/list',"UserController@getList")->name("user.list");
	Route::post('user/count', "UserController@userCount")->name("user.count");
	Route::get('user/profile/{key}', "UserController@viewProfile")->name("user.profile");
	Route::post('user/status', "UserController@updateStatus")->name("user.status");
	Route::post('user/block', "UserController@updateBlock")->name("user.block");
	Route::post('user/destroy',"UserController@destroy")->name("user.destroy");

	Route::get('donate',"AdminHomeController@index")->name("donate");
	Route::post('doner/count', "AdminHomeController@donerCount")->name("doner.count");
	Route::post('donate/list',"AdminHomeController@donateList")->name("donate.list");

	Route::get('contact',"AdminHomeController@contact")->name("contact");
	Route::post('contact/count', "AdminHomeController@contactCount")->name("contact.count");
	Route::post('contact/list',"AdminHomeController@contactList")->name("contact.list");
});

Route::get('/dashboard', 'HomeController@index')->name('home');

Route::get('/visit-website', function(){
	return view('web.visit-website');
});

resources/views/admin/layouts/app.blade.php
@php

    $user = Auth::Guard('admin')->user();
    if($user == false)
    {
      redirect(route("private.login"));
    }
    $currentUrl = url()->current();
@endphp
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <title>{{ config('app.name', 'NpCharity') }} @isset($title) :: {{ $title }} @endisset</title>
    <meta content='width=device-width, initial-scale=1.0, shrink-to-fit=no' name='viewport' />
    <link rel="icon" href="{{ asset('common/img/logo/favicon.png') }}" type="image/x-icon"/>

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">
    
    <!-- Fonts and icons -->
    <script src="{{ asset('admin/assets/js/plugin/webfont/webfont.min.js') }}"></script>
    <script>
        WebFont.load({
            google: {"families":["Lato:300,400,700,900"]},
            custom: {"families":["Flaticon", "Font Awesome 5 Solid", "Font Awesome 5 Regular", "Font Awesome 5 Brands", "simple-line-icons"], urls: ['{{ asset('admin/assets/css/fonts.min.css') }}']},
            active: function() {
                sessionStorage.fonts = true;
            }
        });
    </script>

    <!-- CSS Files -->
    <!-- <link rel="stylesheet" href="{{ asset('admin/assets/css/bootstrap.min.css') }}"> -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">

    <!-- CSS Just for demo purpose, don't include it in your project -->
    <link rel="stylesheet" href="{{ asset('admin/assets/css/demo.css') }}">
    
    <!-- Datatable CSS -->
    <link rel="stylesheet" href="{{ asset('common/vendor/datatable/datatables.min.css') }}">

    <!-- X Editable CSS -->
    <link rel="stylesheet" href="{{ asset('common/vendor/x-editable/css/bootstrap-editable.css') }}">

    <!-- Select 2 CSS -->
    <link rel="stylesheet" href="{{ asset('common/vendor/select2/css/select2.min.css') }}">

    <!-- Date Range Picker CSS -->
    <link rel="stylesheet" href="{{ asset('common/vendor/daterangepicker/daterangepicker.css') }}">

    <!-- Image Picker CSS -->
    <link rel="stylesheet" href="{{ asset('common/vendor/fileinput/css/jasny-bootstrap.min.css') }}">

    <link rel="stylesheet" href="{{ asset('admin/assets/css/atlantis.css') }}">

    <link rel="stylesheet" href="{{ asset('common/css/style.css') }}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ekko-lightbox/5.3.0/ekko-lightbox.css">
    @stack("css")

</head>
<body>
    <div class="wrapper">
        <div class="main-header">
            <!-- Logo Header -->
            <div class="logo-header text-center" data-background-color="blue">
                
                <a href="{{ route("private.dashboard") }}" class="logo">
                    <img src="{{ asset('common/img/logo/logo-small.png') }}" alt="navbar brand" class="navbar-brand w-50">
                </a>
                <button class="navbar-toggler sidenav-toggler ml-auto" type="button" data-toggle="collapse" data-target="collapse" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon">
                        <i class="icon-menu"></i>
                    </span>
                </button>
                <button class="topbar-toggler more"><i class="icon-options-vertical"></i></button>
                <div class="nav-toggle">
                    <button class="btn btn-toggle toggle-sidebar">
                        <i class="icon-menu"></i>
                    </button>
                </div>
            </div>
            <!-- End Logo Header -->

            <!-- Navbar Header -->
            <nav class="navbar navbar-header navbar-expand-lg" data-background-color="blue2">
                
                <div class="container-fluid">
                    <ul class="navbar-nav topbar-nav ml-md-auto align-items-center">
                        <li class="nav-item toggle-nav-search hidden-caret">
                            <a class="nav-link" data-toggle="collapse" href="#search-nav" role="button" aria-expanded="false" aria-controls="search-nav">
                                <i class="fa fa-search"></i>
                            </a>
                        </li>
                        
                        <li class="nav-item dropdown hidden-caret">
                            <a class="nav-link dropdown-toggle" href="#" id="notifDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="fa fa-bell"></i>
                                <span class="notification">0</span>
                            </a>
                            <ul class="dropdown-menu notif-box animated fadeIn" aria-labelledby="notifDropdown">
                                <li>
                                    <div class="dropdown-title">You have 0 new notification</div>
                                </li>
                            </ul>
                        </li>
                        
                        <li class="nav-item dropdown hidden-caret">
                            <a class="dropdown-toggle profile-pic" data-toggle="dropdown" href="#" aria-expanded="false">
                                <div class="avatar-sm">
                                    <img src="{{ empty($user->profile_pic) ? avatar($user->name) : asset($user->profile_pic) }}" alt="..." class="avatar-img rounded-circle">
                                </div>
                            </a>
                            <ul class="dropdown-menu dropdown-user animated fadeIn">
                                <div class="dropdown-user-scroll scrollbar-outer">
                                    <li>
                                        <div class="user-box">
                                            <div class="avatar-lg"><img src="{{ empty($user->profile_pic) ? avatar($user->name) : asset($user->profile_pic) }}" alt="image profile" class="avatar-img rounded"></div>
                                            <div class="u-text">
                                                <h4>{{ $user->name }}</h4>
                                                <p class="text-muted">{{ $user->email }}</p>
                                                <a href="{{ route("private.myprofile") }}" class="btn btn-xs btn-secondary btn-sm">View Profile</a>
                                            </div>
                                        </div>
                                    </li>
                                    <li>
                                        <div class="dropdown-divider"></div>
                                        <a class="dropdown-item" href="{{ route('private.logout') }}">Logout</a>
                                    </li>
                                </div>
                            </ul>
                        </li>
                    </ul>
                </div>
            </nav>
            <!-- End Navbar -->
        </div>

        <!-- Sidebar -->
        <div class="sidebar sidebar-style-2">           
            <div class="sidebar-wrapper scrollbar scrollbar-inner">
                <div class="sidebar-content">
                    <ul class="nav nav-primary">
                        <li class="nav-item @if($currentUrl == route("private.dashboard")) active @endif">
                            <a href="{{ route("private.dashboard") }}">
                                <i class="fas fa-home"></i>
                                <p>Dashboard</p>
                                <!-- <span class="caret"></span> -->
                            </a>
                        </li>
                        <li class="nav-item @if($currentUrl == route("private.donate")) active @endif">
                            <a href="{{ route('private.donate') }}">
                                <i class="fas fa-donate"></i>
                                <p>Donated</p>
                                <!-- <span class="caret"></span> -->
                            </a>
                        </li>
                        <li class="nav-item @if($currentUrl == route("private.contact")) active @endif">
                            <a href="{{ route('private.contact') }}">
                                <i class="fas fa-envelope"></i>
                                <p>Contacts</p>
                                <!-- <span class="caret"></span> -->
                            </a>
                        </li>
                        <li class="nav-item @if($currentUrl == route("private.users")) active @endif">
                            <a href="{{ route('private.users') }}">
                                <i class="fas fa-users"></i>
                                <p>Users</p>
                                <!-- <span class="caret"></span> -->
                            </a>
                        </li>
                        
                    </ul>
                </div>
            </div>
        </div>
        <!-- End Sidebar -->

        <div class="main-panel">
            <div class="content">
                @yield('content')
                
            </div>

            <footer class="footer">
                <div class="container-fluid">
                    <div class="copyright ml-auto">
                        &copy; {{ date('Y') }}, Npcharity</a>
                    </div>              
                </div>
            </footer>
        </div>
    </div>
    <!--   Core JS Files   -->
    
    @include('includes.modal')

    <script src="{{ asset('js/app.js') }}" ></script>

    <!-- jQuery UI -->
    <script src="{{ asset('admin/assets/js/plugin/jquery-ui-1.12.1.custom/jquery-ui.min.js') }}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.18.1/moment.min.js"></script>
    <script src="{{ asset('admin/assets/js/plugin/jquery-ui-touch-punch/jquery.ui.touch-punch.min.js') }}"></script>
    <script src="{{ asset('admin/assets/js/plugin/jquery.magnific-popup/jquery.magnific-popup.min.js') }}"></script>
    
    <!-- jQuery Scrollbar -->
    <script src="{{ asset('admin/assets/js/plugin/jquery-scrollbar/jquery.scrollbar.min.js') }}"></script>
    <!-- Bootstrap Notify -->
    <script src="{{ asset('admin/assets/js/plugin/bootstrap-notify/bootstrap-notify.min.js') }}"></script>

    <!-- Emoji -->
    <script src="//twemoji.maxcdn.com/2/twemoji.min.js?12.0.0"></script>

    <!-- Sweet Alert -->
    <script src="{{ asset('admin/assets/js/plugin/sweetalert/sweetalert.min.js') }}"></script>

    <!-- Atlantis JS -->
    <script src="{{ asset('admin/assets/js/atlantis.js') }}"></script>
    <!-- Data Table JS -->
    <script src="{{ asset('common/vendor/datatable/datatables.min.js') }}"></script>
    
    <!-- X Editable JS -->
    <script src="{{ asset('common/vendor/x-editable/js/bootstrap-editable.min.js') }}"></script>

    <!-- Select 2 -->
    <script src="{{ asset('common/vendor/select2/js/select2.full.min.js') }}"></script>
    
    <!-- Daterange Picker -->
    <script src="{{ asset('common/vendor/daterangepicker/daterangepicker.js') }}"></script>

    <!-- Image Picker -->
    <script src="{{ asset('common/vendor/fileinput/js/jasny-bootstrap.min.js') }}"></script>
    <script src="{{ asset('common/vendor/fileinput/js/fileinput.js') }}"></script>
    
    <!-- Validate -->
    <script src="{{ asset('common/vendor/validate/jquery.validate.min.js') }}"></script>
    <script src="{{ asset('common/vendor/validate/additional-methods.js') }}"></script>

    <script src="{{ asset('common/js/script.js') }}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/ekko-lightbox/5.3.0/ekko-lightbox.js"></script>
    <script src="{{ asset('admin/assets/js/plugin/chart.js/chart.min.js') }}"></script>
    <script>
        var dateFormat = "{{ config("site.date_format.front") }}";
        var dateTimeFormat = "{{ config("site.date_time_format.front") }}";
        var notify = "";
        //Initialize Emoji
        $('body').bind("DOMSubtreeModified",function(){
            twemoji.parse(document.body);
        });
        $(function(){
            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                }
            });
            $( document ).ajaxError(function( event, request, settings ) {
                notifyWarning("Something went wrong");
            });
        });

        $('.image-gallery').magnificPopup({
            delegate: 'a', 
            type: 'image',
            removalDelay: 300,
            gallery:{
                enabled:true,
            },
            mainClass: 'mfp-with-zoom', 
            zoom: {
                enabled: true, 
                duration: 300,
                easing: 'ease-in-out',
                opener: function(openerElement) {
                    return openerElement.is('img') ? openerElement : openerElement.find('img');
                }
            }
        });

    </script>

    @stack("js")

    @stack("include_js")
    
</body>
</html>

{{-- asset('admin/assets/img/profile.jpg') --}}

resources/views/admin/layouts/guest.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
	<meta http-equiv="X-UA-Compatible" content="IE=edge" />

	<title>{{ config('app.name', 'Highlight') }} @isset($title) :: {{ $title }} @endisset</title>
	
	<meta content='width=device-width, initial-scale=1.0, shrink-to-fit=no' name='viewport' />
	<link rel="shortcut icon" href="{{ asset('common/img/logo/favicon.png') }}" type="image/x-icon"/>
	
	<!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

	<!-- Fonts and icons -->
	<script src="{{ asset('admin/assets/js/plugin/webfont/webfont.min.js') }}"></script>
	<script>
		WebFont.load({
			google: {"families":["Lato:300,400,700,900"]},
			custom: {"families":["Flaticon", "Font Awesome 5 Solid", "Font Awesome 5 Regular", "Font Awesome 5 Brands", "simple-line-icons"], urls: ['{{ asset('admin/assets/css/fonts.min.css') }}']},
			active: function() {
				sessionStorage.fonts = true;
			}
		});
	</script>
	
	<!-- CSS Files -->
	<link rel="stylesheet" href="{{ asset('css/app.css') }}">
	<link rel="stylesheet" href="{{ asset('admin/assets/css/atlantis.css') }}">
	<link rel="stylesheet" href="{{ asset('common/css/style.css') }}">
	@stack("css")
</head>
<body class="login">

	@yield("content")
	
	<script src="{{ asset('js/app.js') }}"></script>
	<script src="{{ asset('admin/assets/js/plugin/jquery-ui-1.12.1.custom/jquery-ui.min.js') }}"></script>
	<script src="{{ asset('admin/assets/js/atlantis.js') }}"></script>
	<script src="{{ asset('common/js/script.js') }}"></script>
	<script src="{{ asset('common/vendor/validate/jquery.validate.min.js') }}"></script>
	<script src="{{ asset('common/vendor/validate/additional-methods.js') }}"></script>
	<!-- Bootstrap Notify -->
	<script src="{{ asset('admin/assets/js/plugin/bootstrap-notify/bootstrap-notify.min.js') }}"></script>

	@stack("js")
</body>
</html>