routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', function () {
    return view('web.login');
});
/*Route::prefix("private")->name("private.")->namespace("Admin")->group(function(){
	
	Route::get('/login', 'Auth\LoginController@showLoginForm');
	Route::post('/login-user', 'Auth\LoginController@login')->name('login');
	Route::get('/register', 'Auth\RegisterController@showRegistrationForm');
	Route::post('/store', 'Auth\RegisterController@register')->name('register');
	Route::get('/logout', 'Auth\LoginController@logout')->name('logout');
});*/


Auth::routes();
Route::middleware('auth')->group( function(){
	//User Routes
	Route::get('users',"UserController@index")->name("users");
	Route::post('user/list',"UserController@getList")->name("user.list");
	Route::post('user/count', "UserController@userCount")->name("user.count");
	Route::get('myProfile', "UserController@myProfile")->name("user.profile");
	Route::post('user/status', "UserController@updateStatus")->name("user.status");
	Route::post('user/block', "UserController@updateBlock")->name("user.block");
	Route::post('user/destroy',"UserController@destroy")->name("user.destroy");
	Route::post('profile-update', "UserController@profileUpdate")->name("user.profileUpdate");
	Route::post('password-update', "UserController@passwordUpdate")->name("user.passwordUpdate");

	//Main Folder Route
	Route::post('/add-mainfolder',"MainFolderController@store")->name("users.main-folder");
	Route::post('/get-mainfolder',"MainFolderController@getList")->name("users.get-mainfolder");
	Route::post('/edit-mainfolder',"MainFolderController@edit")->name("users.edit-mainfolder");
	Route::put('/update-mainfolder/{mainFolder}', 'MainFolderController@update')->name('users.update-mainfolder');
	Route::get('/get-folder/{mainFolder}', 'MainFolderController@show')->name('users.show');

	Route::get('/logout', function(){
		auth()->logout();
		return redirect('/')->cookie(cookie()->forget('user_id'));
	});
});

Route::get('admin/login', 'Admin\Auth\LoginController@showLoginForm')->name('admin.login');
Route::post('/login-user', 'Admin\Auth\LoginController@login')->name('admin.login.user');

Route::prefix("private")->middleware('auth:admin')->name("private.")->namespace("Admin")->group( function(){
	Route::get('dashboard', "DashboardController@index")->name('dashboard');
	Route::get('/home', 'AdminController@index')->name('home');
	//Route::get('/login', 'Auth\LoginController@showLoginForm')->name('form');
	//Route::post('/login-user', 'Auth\LoginController@login')->name('login');
	Route::get('/register', 'Auth\RegisterController@showRegistrationForm');
	Route::post('/store', 'Auth\RegisterController@register')->name('register');
	Route::get('/logout', 'Auth\LoginController@logout')->name('logout');

	/*//Admin User related Routes
	Route::get('adminuser/list', "AdminUserController@index")->name("adminusers");
	Route::post('adminuser/list', "AdminUserController@getList")->name("adminuser.list");
	Route::post('adminuser/create', "AdminUserController@create")->name("adminuser.create");
	Route::post('adminuser/edit', "AdminUserController@edit")->name("adminuser.edit");
	Route::post('adminuser/update', "AdminUserController@update")->name("adminuser.update");
	Route::post('adminuser/status', "AdminUserController@updateStatus")->name("adminuser.status");
	Route::post('adminuser/destroy', "AdminUserController@destroy")->name("adminuser.destroy");
	Route::get('adminuser/profile/{key}', "AdminUserController@viewProfile")->name("adminuser.profile");
	
	Route::post('password-update', "AdminUserController@passwordUpdate")->name("passwordUpdate");
	Route::post('profile-update', "AdminUserController@profileUpdate")->name("profileUpdate");*/
	Route::get('adminuser/list', "AdminUserController@index")->name("adminusers");
    Route::get('my-profile', "AdminUserController@myProfile")->name("myprofile");
    Route::post('password-update', "AdminUserController@passwordUpdate")->name("passwordUpdate");
	Route::post('profile-update', "AdminUserController@profileUpdate")->name("profileUpdate");
	Route::post('dashboard-chart', "AdminUserController@barChart")->name('dashboard.chart');

	//Admin User Type Routes
	Route::get('admin-type', "AdminTypeController@index")->name("admintypes");
	Route::post('admin-type/list', "AdminTypeController@getUserTypeList")->name("admintype.list");
	Route::post('admin-type/create', "AdminTypeController@create")->name("admintype.create");
	Route::post('admin-type/edit', "AdminTypeController@edit")->name("admintype.edit");
	Route::post('admin-type/update', "AdminTypeController@update")->name("admintype.update");
	Route::post('admin-type/status', "AdminTypeController@updateStatus")->name("admintype.status");
	Route::post('admin-type/destroy', "AdminTypeController@destroy")->name("admintype.destroy");


	//Question Routes
	Route::get('question', "QuestionController@index")->name("questions")->middleware("ican:question.view");
	Route::post('question/list', "QuestionController@getList")->name("question.list")->middleware("ican:question.view");
	Route::post('question/create', "QuestionController@create")->name("question.create")->middleware("ican:question.create");
	Route::post('question/edit', "QuestionController@edit")->name("question.edit")->middleware("ican:question.edit");
	Route::post('question/update', "QuestionController@update")->name("question.update")->middleware("ican:question.edit");
	Route::post('question/status', "QuestionController@updateStatus")->name("question.status")->middleware("ican:question.edit");
	Route::post('question/destroy', "QuestionController@destroy")->name("question.destroy")->middleware("ican:question.delete");

	//User Routes
	Route::get('users',"UserController@index")->name("users");
	Route::post('user/list',"UserController@getList")->name("user.list");
	Route::post('user/count', "UserController@userCount")->name("user.count");
	Route::get('user/profile/{key}', "UserController@viewProfile")->name("user.profile");
	Route::post('user/status', "UserController@updateStatus")->name("user.status");
	Route::post('user/block', "UserController@updateBlock")->name("user.block");
	Route::post('user/destroy',"UserController@destroy")->name("user.destroy");

	Route::get('donate',"AdminHomeController@index")->name("donate");
	Route::post('doner/count', "AdminHomeController@donerCount")->name("doner.count");
	Route::post('donate/list',"AdminHomeController@donateList")->name("donate.list");

	Route::get('contact',"AdminHomeController@contact")->name("contact");
	Route::post('contact/count', "AdminHomeController@contactCount")->name("contact.count");
	Route::post('contact/list',"AdminHomeController@contactList")->name("contact.list");
});

Route::get('/dashboard', 'HomeController@index')->name('home');

Route::get('/visit-website', function(){
	return view('web.visit-website');
});

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Laravel\Passport\HasApiTokens;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Database\Eloquent\SoftDeletes;

class User extends Authenticatable
{
    use Notifiable, SoftDeletes, HasApiTokens;
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password','phone', 'profile_pic', 'created_by', 'updated_by',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/API/UserController.php
<?php

namespace App\Http\Controllers\API;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\User; 
use Auth; 
use Validator;
use Illuminate\Support\Facades\Cookie;

class UserController extends Controller
{
    public $successStatus = 200;

    public function login(Request $request){ 
        $validator = Validator::make($request->all(), [ 
            'email' => 'required|email', 
            'password' => 'required'
        ]);
        if ($validator->fails()) { 
            return response()->json(['error'=>$validator->errors()], 401);            
        }

        if(Auth::attempt(['email' => $request->email, 'password' => $request->password])){ 
            $user = Auth::user(); 
            $result = [
                'token' => $user->createToken('TechZAR')->accessToken,
                'user' => $user
            ];
            return response()->json($result, $this->successStatus); 
        } 
        else{ 
            return response()->json(['error'=>'Unauthorised'], 401); 
        } 
    }

    public function getUserId(Request $request){
        return response()->json($_COOKIE['user_id']);
    }
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Maatwebsite\Excel\Facades\Excel;
use Auth;
use Validator;
use Avatar;
use Yajra\Datatables\Datatables;
use App\User;
use App\UserProfile;
use Carbon\Carbon;
use Carbon\CarbonPeriod;
use Illuminate\Contracts\Encryption\DecryptException;

class UserController extends Controller
{
    
    public function index()
    {
        $response_data["title"] = __("title.private.user_list");
        return view("admin.user.list")->with($response_data);
    }

    public function userCount()
    {
        $response_data = User::count();
        return response()->json($response_data);
    }

    //Blocked User
    public function updateBlock(Request $request)
    {
        $validator = Validator::make($request->all(), [
                    "value" => "required|in:0,1",
                    "pk" => "required|exists:users,id",
                ]);
        //dd($request->all());
        if(!$validator->fails()){
            $user = User::find($request->pk);
            if($request->value == 1)
            {
                $user->blocked_at = now();
            }
            elseif($request->value==0)
            {
                $user->blocked_at =NULL;
            }
            
            if($user->save()){
                $response_data = ["success" => 1, "message" => __("validation.update_success", ["attr" => "User Blocked"])];
            }else{
                $response_data = ["success" => 0, "message" => __("site.server_error")];
            }
        }else{
            $response_data = ["success" =>  0, "message" => __("validation.refresh_page")];
        }
       return response()->json($response_data);
    }



    public function getList(Request $request)
    {
        $query = User::select();
        if($request->has("status") && $request->status != ""){
            $query->whereActive($request->status);
        }
        if ($request->filled('start_date')) {
            $query->whereDate('created_at', '>=', "{$request->get('start_date')}");
        }

        if ($request->filled('end_date')) {
            $query->whereDate('created_at', '<=', "{$request->get('end_date')}");
        }
       return Datatables::of($query->get())->make(true);
    }

    //User Delete
    public function destroy(Request $request)
    {

        $validator = Validator::make($request->all(),
            [
              'data' => 'required|exists:users,id,deleted_at,NULL',
            ]);
            
        if (!$validator->fails()) 
        { 
            $user = User::find($request->data);    
            if($user->delete()){
                $response_data =  ['success' => 1, 'message' => __('validation.delete_success',['attr'=>'User'])]; 
            }else{
                
                $response_data =  ['success' => 1, 'message' => __('site.server_error')]; 
            }

        }else
        {
            $response_data =  ['success' => 0, 'message' => __('validation.refresh_page')];
        }

        return response()->json($response_data);
    }

    public function logout()
    {
    	Auth::logout();
        return redirect(route("login"));
    }

}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Auth;
use Validator;
use Yajra\Datatables\Datatables;
use App\User;
use App\Highlight;
use App\FolderColor;
use Illuminate\Support\Facades\Hash;
use Illuminate\Contracts\Encryption\DecryptException;

class UserController extends Controller
{

    public function index()
    {
        $title = __("title.private.users");
        $folder_colors = FolderColor::where('folder_id', 1)->get();
        $highlights = Highlight::where('folder_id', 1)->get();

        $list = [];
        foreach($highlights as $item){
            $count = isset($list[$item->page_url]) ? $list[$item->page_url]['count'] + 1 : 1;
            if(!isset($list[$item->page_url]))
                $list[$item->page_url] = ['title' => $item->page_title, 'date' => $item->created_at, 'count' => $count];
            $list[$item->page_url]['highlights'][] = ['color_class' => $item->color->color_code, 'content' => $item->content];
        }

        // dd($list);

        return view("web.user-list", compact('title', 'list', 'folder_colors'));
    }

    public function userCount()
    {
        $user= Auth::user();
        $response_data = Donate::whereUserId($user->id)->count();
        return response()->json($response_data);
    }
    public function myProfile()
    {
        $response_data["title"] = __("title.private.my_profile");
        $response_data["profile"] = Auth::user();
        return view("web.user.myprofile")->with($response_data);
    }

     public function profileUpdate(Request $request)
    {
        $user = auth()->user();
        $validator = Validator::make($request->all(),
            [
              'name'        => 'required|min:'.limit("name.min").'|max:'.limit("name.max").'|valid_name|not_exists:admin_users,name,deleted_at,NULL',
              'email'       => 'required|email|min:'.limit("email.min").'|max:'.limit("email.max").'|unique:users,email,'.$user->id.',id,deleted_at,NULL',
              'phone'       => 'required|numeric|digits:'.limit("phone.max").'|unique:users,phone,'.$user->id.',id,deleted_at,NULL',
            ]);
        if(!$validator->fails()){

            $user->name        = $request->name;
            $user->email       = $request->email;
            $user->phone       = $request->phone;
            if($user->save()){
                $response_data = ["success" => 1, "message" => __("validation.update_success", ["attr" => "Profile"])];
            }else{
                $response_data = ["success" => 0, "message" => __("site.server_error")];
            }

        }else{
            $response_data = ["success" => 0, "message" => __("validation.check_fields"), "errors" => $validator->errors()->toArray()];
        }
        return response()->json($response_data);
    }

    public function passwordUpdate(Request $request)
    {
        $validator = Validator::make($request->all(),
        [
            "current_password"  => "required",
            'password'          => 'required|confirmed|min:'.limit("password.min").'|max:'.limit("password.max").'|password|different:current_password',
        ]);

        if(!$validator->fails()){
            $user = auth()->user();
            if (Hash::check($request->current_password, $user->password)) {
                $user->password = bcrypt($request->password);
                if($user->save()){
                    $response_data = ["success" => 1, "message" => __("validation.update_success", ["attr" => "Password"])];
                }else{
                    $response_data = ["success" => 0, "message" => __("site.server_error")];
                }
            }else{

                $response_data = ["success" => 0,  "message" => __("site.invalid_password")];
            }
        }else{
            $response_data = ["success" => 0,  "message" => __("validation.check_fields"), "errors" => $validator->errors()->toArray()];
        }

        return response()->json($response_data);

    }

    public function getList(Request $request)
    {
        $query = Donate::select();
        $user  = auth()->user();
        if ($request->filled('start_date')) {
            $query->whereDate('created_at', '>=', "{$request->get('start_date')}");
        }

        if ($request->filled('end_date')) {
            $query->whereDate('created_at', '<=', "{$request->get('end_date')}");
        }
       return Datatables::of($query->whereUserId($user->id)->get())->make(true);
    }
}

resources/views/admin/user/list.blade.php
@extends("admin.layouts.app")

@section("content")
<div class="page-inner">
	<div class="page-header">
		<h4 class="page-title">{{$title}}</h4>
		<ul class="breadcrumbs">
			<li class="nav-home">
				<a href="#">
					<i class="flaticon-home"></i>
				</a>
			</li>
			<li class="separator">
				<i class="flaticon-right-arrow"></i>
			</li>
			<li class="nav-item">
				<a href="{{ route('private.dashboard') }}">Dashboard</a>
			</li>
			<li class="separator">
				<i class="flaticon-right-arrow"></i>
			</li>
			<li class="nav-item">
				<a href="#">{{ $title }}</a>
			</li>
		</ul>
	</div>
	<div class="row">
		<div class="col-md-12">
			<div class="card">
					<div class="card-header">
						<div class="row">
						<div class="col-md-6 col-sm-6">
						<h4 class="card-title">{{ $title }}</h4>
						</div>
						<div class="col-md-6 col-sm-6">
						 <h6 class="float-right">Total User&nbsp;(<span class="user-count"></span>)</h6>
						</div>
					</div>
				
					</div>
					
				<div class="card-body">
					<div class="row p-2 filter-cont mb-4">
						<!-- <div class="col-md-3 pl-0">
							<div class="form-group pt-0">
								<label>Status</label>
								<select class="select-filter form-control" data-placeholder="Select a Status" id="status-filter">
	                              	<option value="">All</option>
	                              	@foreach(config("site.status") as $key => $status)
		                              	<option value="{{ $key }}">{{ $status }}</option>
	                              	@endforeach

								</select>
							</div>
						</div> -->
						<div class="col-md-3 pl-0 push-right">
							<div class="form-group pt-0">
								<label>Created Date</label>
								<input type="text" class="form-control bg-white" readonly id="date-filter">
							</div>
						</div>
						<div class="col-md-3 pl-0 " style="display: none;">
							<div class="form-group pt-10 float-right">
								<button class="btn btn-primary btn-border btn-round export">Exports</button>
							</div>
						</div> 
					</div>
					<div class="table-responsive">
						<table id="record-table" class="display table table-striped table-hover w-100 table-head-bg-primary" >
							<thead>
								<tr>
									<th>Name</th>
									<th>Email</th>
									<th>Mobile</th>
									<th>Created On</th>
									<th>Block</th>
									<th>Action</th>
								</tr>
							</thead>
							<tbody>
								
							</tbody>
						</table>
					</div>
				</div>
			</div>
		</div>


	</div>
</div>

@endsection
@push("css")
<style>
.export:hover 
{
    background-color: #1572E8 !important;
    color: #FFF!important;
}
</style>
@endpush

@push("js")

	<script type="text/javascript">

		var delete_url = "{{ route('private.user.destroy') }}";
		var table;
		var startDate = moment().startOf('year').format('YYYY-MM-DD');
		var endDate = moment().format('YYYY-MM-DD');
		
		$(document).ready(function() {
			$.ajax({
  					url: "{{ route('private.user.count') }}",
  					type: "POST",
  					dataType: "json",
  					success: function(response){
            		 $('.user-count').html(response);
           				},
				});

			// $('.export').click(function(){
			//     var gender_type = $("#gender-filter").val();    
			// 	var status = $("#status-filter").val();	    
			// 	if(gender_type=="")
			// 	{
			// 		gender_type=11;
			// 	}
			// 	if(status=="")
			// 	{
			// 		status=11;
			// 	}
			// 		window.location.href = "{{URL('private/user/export')}}/"+gender_type+"/"+status+"/"+startDate+"/"+endDate;
			// });
			
				
	    	table = $('#record-table').dataTable({
				"oLanguage": {
			        "sEmptyTable": "{{ __("site.no_data", ["attr" => "User"]) }}"
			    },
	            "processing": true,
	            "serverSide": true,
	            "ajax": {
	                "url": "{{ route("private.user.list") }}",
	                "type": "POST",
	                data: function (d) { 
						d.status = $("#status-filter").val()     
						d.start_date = startDate
						d.end_date = endDate
	                },
	            },
	            
	            "columns": [
	                    { "data": "name" },
	                    { "data": "email" },
	                    { "data": "phone" },
	                    // { "render":  function ( data, type, row ){ return row.tel_code+" "+row.phone}, "name": "phone"  },
						{ "data": "created_at",
							"render": function ( data, type, row ) {
								return moment(row.created_at).format(dateFormat);
							},
							"name": "created_at" 
						},
						{ "data": "block",
	                       "render": function ( data, type, row ) {
		                       	if(!row.blocked_at){
		                       		return `<a href="javascript:;" class="badge block_edit"  data-type="select" data-pk="${row.id}" data-value="0" data-original-title="Select Status"> </a>`;
		                       	}else
		                       	{
		                       		return `<a href="javascript:;" class="badge block_edit"  data-type="select" data-pk="${row.id}" data-value="1" data-original-title="Select Status"> </a>`;
		                       	}

	                        },
	                        "name": "blocked_at"  
						},
	                    {   "mRender": function ( data, type, row ) 
	                        {
	                        	var btn = `<div class="form-button-action"><button type="button" data-toggle="tooltip" title="" class="btn btn-link btn-danger delete-data"  data-id="${row.id}" data-original-title="Remove"> <i class="fa fa-times"></i> </button> </div>`; 
	                            return btn;       
	                         }
	                    }
	                ],

	               createdRow: function( row, data, dataIndex ) {
	                            $(row).find( '.block_edit' ).editable({
                                url: "{{ route('private.user.block') }}",
                                success: function(response, newValue) {
                                    if(response.success == 0) return response.message; //msg will be shown in editable form
									table.fnDraw();
                                },

                                inputclass: 'form-control',
                                source: [{
                                    value: 1,
                                    text: 'Block'
                                }, {
                                    value: 0,
                                    text: 'Unblock'
                                }],
                                display: function(value, sourceData) {
                                    var cls = {
                                            1: "badge-danger",
                                            0: "badge-success"
                                        },
                                        rmcls = {
                                            0: "badge-danger",
                                            1: "badge-success"
                                        },
                                        elem = $.grep(sourceData, function(o) {
                                            return o.value == value;
                                        });

                                    if (elem.length) {
                                        $(this).text(elem[0].text).attr("data-value", value).removeClass( rmcls[value]);
                                        $(this).addClass( cls[value]);
                                    } else {
                                        $(this).empty();
                                    }
                                }
                            });
	                        },
	            "columnDefs": [
		            {  // set default column settings
		                'orderable': false,
		                'targets': [ -1]
		            }, 
		            {
		                "searchable": false,
		                "targets": [ -1]
		            }
				],
				"order": [
					[4, "desc"]
				] 
	        });

			//Table Filter
			$(".filter-cont .select-filter").change(function(){
				table.fnDraw();
			});

			//Initialize Select 2
			$(".select-filter").select2({
				theme: "bootstrap"
			});

			//DateRange Picker
			$("#date-filter").daterangepicker({
				opens: 'left',
				startDate: moment().startOf('year'),
				endDate: moment(),
				locale: {
					format: '{{ config("site.date_format.front") }}'
				},
				maxDate:moment(),
				ranges: {
					'Today': [moment(), moment()],
					'Yesterday': [moment().subtract(1, 'days'), moment().subtract(1, 'days')],
					'Last 7 Days': [moment().subtract(6, 'days'), moment()],
					'Last 30 Days': [moment().subtract(29, 'days'), moment()],
					'This Month': [moment().startOf('month'), moment().endOf('month')],
					'This Year': [moment().startOf('year'), moment().endOf('year')],
					'Last Month': [moment().subtract(1, 'month').startOf('month'), moment().subtract(1, 'month').endOf('month')]
				},
				//autoUpdateInput: false,
			}, function(start, end, label) {
				startDate = start.format('YYYY-MM-DD');
				endDate =  end.format('YYYY-MM-DD');
				table.fnDraw();

			});
	    });
	</script>
@endpush